#!/usr/bin/env bash

set -eo pipefail

# Uninstall all packages
uv pip uninstall --system -r <(uv pip freeze)

# Install requirements
uv pip install --system -r requirements.txt

# Generate lockfile
printf "# THIS IS AN AUTOGENERATED LOCKFILE. DO NOT EDIT MANUALLY.\n" >plugin_scripts/requirements.lock
uv pip freeze >>plugin_scripts/requirements.lock

echo "Requirements locked successfully."
echo "Rebuild containers to verify there are no conflicts."
